/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
import React from 'react';
import './PDFViewer.css';
import { Attachment } from '../../../lib/state';
import { useLiveAPIContext } from '../../../contexts/LiveAPIContext';

interface PDFViewerProps {
  attachment: Attachment;
}

const PDFViewer: React.FC<PDFViewerProps> = ({ attachment }) => {
  const { user } = useLiveAPIContext();

  const handleDownload = (e: React.MouseEvent) => {
    e.preventDefault();
    const link = document.createElement('a');
    link.href = attachment.dataUrl;
    link.download = attachment.name;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };
  
  const mailSubject = `Document: ${attachment.name}`;
  const mailBody = `Hello,\n\nPlease find the document "${attachment.name}" attached for your review.\n\nThis document was generated by Kithai.\n\nInstructions: Please download the file from the chat first, then attach it to this email before sending.`;
  const mailtoLink = `mailto:${user?.email || ''}?subject=${encodeURIComponent(mailSubject)}&body=${encodeURIComponent(mailBody)}`;

  return (
    <div className="pdf-viewer-container">
      <div className="pdf-viewer-header">
        <div className="pdf-viewer-info">
          <span className="icon">picture_as_pdf</span>
          <span className="pdf-viewer-filename">{attachment.name}</span>
        </div>
        <div className="pdf-viewer-actions">
          <a href={mailtoLink} className="pdf-action-btn" title="Email document" target="_blank" rel="noopener noreferrer">
            <span className="icon">email</span>
          </a>
          <button onClick={handleDownload} className="pdf-action-btn" title="Download PDF">
            <span className="icon">download</span>
          </button>
        </div>
      </div>
      <div className="pdf-viewer-content">
        <iframe
          src={attachment.dataUrl}
          title={attachment.name}
          width="100%"
          height="100%"
          style={{ border: 'none' }}
        />
      </div>
    </div>
  );
};

export default PDFViewer;